title: "Lethios' Site"
author: "Lethios"
description: "Welcome to my personal website"

url: "https://lethios.github.io"
baseurl: ""

remote_theme: jekyll/minima

minima:
skin: auto
social_links:
- { platform: github,  user_url: "https://github.com/Lethios" }
- { platform: twitter, user_url: "https://twitter.com/LethiosDev" }

plugins:
  jekyll-feed
  jekyll-seo-tag
  jekyll-remote-theme

feed:
path: feed.xml

exclude:
  README.md
  Gemfile
  Gemfile.lock
  node_modules
  vendor/bundle/
  vendor/cache/
  vendor/gems/
  vendor/ruby/
