title: "Lethios' Site"
author: "Lethios"
description: "Welcome to my personal website"

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    github: Lethios
    twitter: LethiosDev

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
